import type { JobKey, JobProfile } from './types';

export const JOB_PROFILES: Record<JobKey, JobProfile> = {
  fighter: {
    key: 'fighter',
    label: '剑客 / Fighter',
    family: 'warrior',
    notes: '近战稳定，血量高，适合打密集地图；缺点是跑图和远程处理能力一般。',
    baseDpsAtLevel10: 72,
    dpsGrowthPerLevel: 0.085,
    minKillSeconds: 0.85,
    attackTaxSeconds: 0.25,
    rangeScore: 0.35,
    aoeScore: 0.5,
    mobilityScore: 0.45,
    accuracyBase: 52,
    accuracyPerLevel: 1.8,
    survivability: 0.82,
    potionIntensity: 0.78,
    mesoFind: 1,
    preferredLevelDelta: [-3, 4],
  },
  page: {
    key: 'page',
    label: '准骑士 / Page',
    family: 'warrior',
    notes: '容错和防御更高，路线偏安全，极限冲级略慢。',
    baseDpsAtLevel10: 68,
    dpsGrowthPerLevel: 0.08,
    minKillSeconds: 0.9,
    attackTaxSeconds: 0.25,
    rangeScore: 0.35,
    aoeScore: 0.46,
    mobilityScore: 0.42,
    accuracyBase: 52,
    accuracyPerLevel: 1.7,
    survivability: 0.92,
    potionIntensity: 0.65,
    mesoFind: 1,
    preferredLevelDelta: [-4, 3],
  },
  spearman: {
    key: 'spearman',
    label: '枪战士 / Spearman',
    family: 'warrior',
    notes: '攻击范围更舒服，适合高密度地图；药耗和安全性需要权衡。',
    baseDpsAtLevel10: 70,
    dpsGrowthPerLevel: 0.088,
    minKillSeconds: 0.88,
    attackTaxSeconds: 0.28,
    rangeScore: 0.52,
    aoeScore: 0.56,
    mobilityScore: 0.43,
    accuracyBase: 50,
    accuracyPerLevel: 1.75,
    survivability: 0.78,
    potionIntensity: 0.9,
    mesoFind: 1,
    preferredLevelDelta: [-3, 5],
  },
  fire_poison: {
    key: 'fire_poison',
    label: '火毒法师 / Fire-Poison',
    family: 'magician',
    notes: '爆发和属性优势路线明显，但 MP 药耗偏高。第一版先用通用魔法模型估算。',
    baseDpsAtLevel10: 76,
    dpsGrowthPerLevel: 0.09,
    minKillSeconds: 0.75,
    attackTaxSeconds: 0.2,
    rangeScore: 0.72,
    aoeScore: 0.42,
    mobilityScore: 0.55,
    accuracyBase: 90,
    accuracyPerLevel: 2.2,
    survivability: 0.58,
    potionIntensity: 1.35,
    mesoFind: 0.95,
    preferredLevelDelta: [-2, 6],
  },
  ice_lightning: {
    key: 'ice_lightning',
    label: '冰雷法师 / Ice-Lightning',
    family: 'magician',
    notes: '控场和群体效率好，适合密集地图；MP 成本要进评分。',
    baseDpsAtLevel10: 73,
    dpsGrowthPerLevel: 0.088,
    minKillSeconds: 0.78,
    attackTaxSeconds: 0.2,
    rangeScore: 0.72,
    aoeScore: 0.64,
    mobilityScore: 0.55,
    accuracyBase: 90,
    accuracyPerLevel: 2.2,
    survivability: 0.62,
    potionIntensity: 1.28,
    mesoFind: 0.95,
    preferredLevelDelta: [-3, 5],
  },
  cleric: {
    key: 'cleric',
    label: '牧师 / Cleric',
    family: 'magician',
    notes: '安全和续航好，遇到不死系应额外加权；当前数据若无 undead 细节则按保守估算。',
    baseDpsAtLevel10: 64,
    dpsGrowthPerLevel: 0.078,
    minKillSeconds: 0.85,
    attackTaxSeconds: 0.22,
    rangeScore: 0.68,
    aoeScore: 0.48,
    mobilityScore: 0.52,
    accuracyBase: 88,
    accuracyPerLevel: 2.1,
    survivability: 0.8,
    potionIntensity: 0.72,
    mesoFind: 1.02,
    preferredLevelDelta: [-4, 4],
  },
  hunter: {
    key: 'hunter',
    label: '猎人 / Hunter',
    family: 'archer',
    notes: '远程拉扯舒服，惩罚近身密集地图；适合地形开阔、怪物等级贴近的路线。',
    baseDpsAtLevel10: 69,
    dpsGrowthPerLevel: 0.084,
    minKillSeconds: 0.8,
    attackTaxSeconds: 0.18,
    rangeScore: 0.86,
    aoeScore: 0.4,
    mobilityScore: 0.62,
    accuracyBase: 70,
    accuracyPerLevel: 2.4,
    survivability: 0.58,
    potionIntensity: 0.9,
    mesoFind: 1,
    preferredLevelDelta: [-2, 5],
  },
  crossbowman: {
    key: 'crossbowman',
    label: '弩弓手 / Crossbowman',
    family: 'archer',
    notes: '单体效率偏稳，射程好但机动一般；适合低风险站桩点。',
    baseDpsAtLevel10: 71,
    dpsGrowthPerLevel: 0.083,
    minKillSeconds: 0.82,
    attackTaxSeconds: 0.2,
    rangeScore: 0.88,
    aoeScore: 0.36,
    mobilityScore: 0.55,
    accuracyBase: 72,
    accuracyPerLevel: 2.45,
    survivability: 0.56,
    potionIntensity: 0.92,
    mesoFind: 1,
    preferredLevelDelta: [-2, 5],
  },
  assassin: {
    key: 'assassin',
    label: '刺客 / Assassin',
    family: 'rogue',
    notes: '远程、高机动、对补给依赖中等；适合跨图抢高效率点。',
    baseDpsAtLevel10: 74,
    dpsGrowthPerLevel: 0.087,
    minKillSeconds: 0.72,
    attackTaxSeconds: 0.17,
    rangeScore: 0.82,
    aoeScore: 0.28,
    mobilityScore: 0.86,
    accuracyBase: 78,
    accuracyPerLevel: 2.3,
    survivability: 0.6,
    potionIntensity: 0.95,
    mesoFind: 1.05,
    preferredLevelDelta: [-2, 6],
  },
  bandit: {
    key: 'bandit',
    label: '侠客 / Bandit',
    family: 'rogue',
    notes: '近战爆发高但吃操作和地形；更适合怪物密度高但伤害不爆炸的点。',
    baseDpsAtLevel10: 76,
    dpsGrowthPerLevel: 0.086,
    minKillSeconds: 0.74,
    attackTaxSeconds: 0.18,
    rangeScore: 0.42,
    aoeScore: 0.44,
    mobilityScore: 0.82,
    accuracyBase: 76,
    accuracyPerLevel: 2.2,
    survivability: 0.55,
    potionIntensity: 1.08,
    mesoFind: 1.08,
    preferredLevelDelta: [-3, 4],
  },
  brawler: {
    key: 'brawler',
    label: '拳手 / Brawler',
    family: 'pirate',
    notes: '国服/海盗路线预留。当前 zip 若无海盗技能，也能先用战斗参数模拟。',
    baseDpsAtLevel10: 72,
    dpsGrowthPerLevel: 0.086,
    minKillSeconds: 0.78,
    attackTaxSeconds: 0.22,
    rangeScore: 0.48,
    aoeScore: 0.55,
    mobilityScore: 0.68,
    accuracyBase: 68,
    accuracyPerLevel: 2,
    survivability: 0.68,
    potionIntensity: 0.98,
    mesoFind: 1,
    preferredLevelDelta: [-3, 5],
  },
  gunslinger: {
    key: 'gunslinger',
    label: '火枪手 / Gunslinger',
    family: 'pirate',
    notes: '国服/海盗路线预留。远程机动模型，等国服数据补全后可细化。',
    baseDpsAtLevel10: 70,
    dpsGrowthPerLevel: 0.084,
    minKillSeconds: 0.76,
    attackTaxSeconds: 0.18,
    rangeScore: 0.8,
    aoeScore: 0.34,
    mobilityScore: 0.78,
    accuracyBase: 74,
    accuracyPerLevel: 2.2,
    survivability: 0.56,
    potionIntensity: 0.98,
    mesoFind: 1,
    preferredLevelDelta: [-2, 5],
  },
};

export const JOB_OPTIONS = Object.values(JOB_PROFILES);
